title: Maggie Chang
description: Hello! This is Maggie, I like to bridge the gap between complex data and strategic decision-making. With a Master's in data science and real-world experience in performance analysis, I'm passionate about solving complex business problems through data-driven solutions.theme: jekyll-theme-minimal
